### ISSUE TITLE
Handling more interfaces

### ISSUE THREAD

**Issue by slgrobotics** [ipa320/ros_battery_monitoring#2]
@ottojo - I want to use more data from my hardware controller, for which I defined appropriate State interfaces:
```
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "voltage", &battery_.voltage));
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "temperature", &battery_.temperature));
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "current", &battery_.current));
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "charge", &battery_.charge));
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "capacity", &battery_.capacity));
  state_interfaces.emplace_back(hardware_interface::StateInterface(battery_.name, "percentage", &battery_.percentage));
```
But the current _BatteryStateBroadcaster_ code seems to only query "_voltage_" interface. Are there any plans to add code so that the _BatteryState_ message would contain appropriate data? Am I missing something?

```
battery_state_broadcaster:
  ros__parameters:
    sensor_name: "main_battery"
    power_supply_technology: 4
    design_capacity: 20.0
    # https://github.com/ros2/common_interfaces/blob/rolling/sensor_msgs/msg/BatteryState.msg
    # https://github.com/ipa320/ros_battery_monitoring/blob/main/battery_state_broadcaster/src/BatteryStateBroadcaster.cpp
    state_interfaces:
      - voltage
      - temperature
      - current
      - charge
      - capacity
      - percentage
```
 
I can make changes in my fork and contribute, if that makes sense. Thanks!

P.S. [my code](https://github.com/slgrobotics/articubot_one) is for ROS2 Jazzy at this time. So far I am just using its binary (apt-get), which seems to be built from this repository.

**Comment by ottojo** [comment]
Hi!

The only reason why only voltage is populated currently is that our robot only gave us that measurement.
I would welcome any contribution to add more capability here, I don't plan on adding that myself in the near future!

The only request i would have is that the state inferfaces corresponding to the optional fields in the BatteryState message also stay optional here.
Maybe the config could look like that (only a suggestion):

```yaml
battery_state_broadcaster:
  ros__parameters:
    sensor_name: "main_battery"
    power_supply_technology: 4
    design_capacity: 20.0
    # https://github.com/ros2/common_interfaces/blob/rolling/sensor_msgs/msg/BatteryState.msg
    voltage_interface: "battery_voltage" # voltage is a mandatory field, but has a non-default name here
    percentage_interface: "" # a "percentage" interface exists, but is not related to battery state, so explicitly exclude it here
    # a "current" interface does not exist, so it isnt populated in the batterystate message
    # a "temperature" interface exists and matches the field name in the batterystate message, so it's chosen by default
    # ...
```

**Comment by slgrobotics** [comment]
@ottojo - thanks for your insights. I'll try to come up with a working solution soon.

**Comment by slgrobotics** [comment]
@ottojo - a search in GitHub brings this implementation: https://github.com/HarvestX/h6x_ros2_controllers/tree/humble/battery_state_broadcaster

It looks like they provided some flexibility in defining State interfaces. I'll be digging a bit into that code trying to understand it better - it's a bit complicated to me at the moment.

**Comment by slgrobotics** [comment]
@ottojo  - I have a working code here: https://github.com/slgrobotics/ros_battery_monitoring

It is a fork of your repository with changes inspired (a.k.a _copied/pasted_) by the _HarvestX_ code.

It works for me, with the following *controllers.yaml* setup:
```
battery_state_broadcaster:
  ros__parameters:
    sensor_name: "main_battery"
    frame_id: "battery_frame"
    power_supply_technology: 4
    power_supply_status: 3
    power_supply_health: 1
    design_capacity: 20.0
    location: "plucky"
    serial_number: "3.0001"
    # https://github.com/ros2/common_interfaces/blob/rolling/sensor_msgs/msg/BatteryState.msg
    # https://github.com/ipa320/ros_battery_monitoring/blob/main/battery_state_broadcaster/src/BatteryStateBroadcaster.cpp
    state_interfaces:
      - voltage
      - temperature
      - current
      - charge
      - capacity
      - percentage
```
If I shrink it to the minimum, it works with only "_voltage_" interface configured: 
```
battery_state_broadcaster:
  ros__parameters:
    sensor_name: "main_battery"
```
The code needs a bit of cleanup, but I am pretty much ready to create a pull request.

Any ideas? thoughts?
